import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import downGraphic from '../public/lottie/down.json';
import graduationGraphic from '../public/lottie/opt2.json';
import Lottie from "react-lottie";
import { useRef } from 'react';
import RegisterForm from '../components/RegisterForm/RegisterForm';
import Carousel from '../components/Carousel/Carousel';

const Home: NextPage = () => {
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: downGraphic,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice"
    },
  };

  const hatAnimationOptions = {
    loop: true,
    autoplay: true,
    animationData: graduationGraphic,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice"
    }
  }

  const registerContainer = useRef<null | HTMLDivElement>(null);

  const scrollToBottom = () => {
    if (registerContainer && registerContainer.current) {
      registerContainer.current.scrollIntoView({ behavior: "smooth" });
    }
  }


  return (
    <div>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <Lottie
            options={hatAnimationOptions}
            height={400}
            width={500}
            isClickToPauseDisabled          />
        <h1 className={styles.title}>
          Quiz. Learn. Collaborate. 
          </h1>
          <h3 className={styles.h3}>XYZ equips students with the resources required to ace your university assessments.</h3>
          <div className={styles.getStartedButton}
          onClick={() => scrollToBottom()}>
          <h6 className={styles.caption}> Get started</h6>
            <Lottie
            options={defaultOptions}
            height={100}
            width={100}
            />
            </div>
        </div>
        <div className={styles.container}>
          <Carousel nSlides={3} content={[
            { title: "Submit questions", text: "Create questions on topics of your choosing, building a pool of questions for you and your classmates to use.", imgPath: "https://dummyimage.com/600x400/000/fff" },
            { title: "Test yourself", text: "Create questions on topics of your choosing, building a pool of questions for you and your classmates to use.", imgPath: "https://dummyimage.com/600x400/000/fff" },
            {title: "Discuss solutions", text: "Create questions on topics of your choosing, building a pool of questions for you and your classmates to use.", imgPath: "https://dummyimage.com/600x400/000/fff"}
          ]}/>
        </div>
        <div className={styles.container} ref={registerContainer}>
        <h1 className={styles.title}>
          Get started today!
          </h1>
          <RegisterForm />
        </div>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel-logotype-light.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      </div>
  )
}

export default Home
